---
namespace: simeononsecurity
name: "system_update"
description: "Role to automate patching of both Linux and Windows systems."
readme: README.md
version: 1.0.0
homepage: https://simeononsecurity.ch
issues: https://github.com/simeononsecurity/ansible_system_update/issues
repository: https://github.com/simeononsecurity/ansible_system_update
authors:
  - SimeonOnSecurity (https://simeononsecurity.ch)
license_file: LICENSE
tags:
- role
- system
- linux
- windows
build_ignore:
- .github
- .gitattributes
- .gitignore
- .vscode
