---
- name: Run Linux update playbook
  when: ansible_facts['ansible_distribution'] == 'Linux'
  block:
    - import_tasks: linux_update.yml

- name: Run Windows update playbook
  when: ansible_facts['ansible_distribution'] == 'Windows'
  block:
    - import_tasks: windows_update.yml
