---
- name: Run Linux update playbook
  include_task: linux_update.yml
  when: ansible_facts['ansible_distribution'] == 'Linux'

- name: Run Windows update playbook
  include_task: windows_update.yml
  when: ansible_facts['ansible_distribution'] == 'Windows'