---
- name: Run Linux update playbook
  block:
    - include_task: linux_update.yml
  when: ansible_facts['ansible_distribution'] == 'Linux'

- name: Run Windows update playbook
  block:
    - include_task: windows_update.yml
  when: ansible_facts['ansible_distribution'] == 'Windows'
  